---
apiVersion: v1
kind: Namespace
metadata:
  name: nsplease-requests
---
apiVersion: v1
kind: Namespace
metadata:
  name: nsplease-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nsplease
  name: nsplease
  namespace: nsplease-system
spec:
  selector:
    matchLabels:
      app: nsplease
  template:
    metadata:
      labels:
        app: nsplease
    spec:
      serviceAccountName: nsplease
      containers:
      - image: ghcr.io/jpetazzo/nsplease
        name: nsplease
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nsplease
  namespace: nsplease-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nsplease
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  namespace: nsplease-system
  name: nsplease
